image: maven:3.9-eclipse-temurin-24

stages:
  - deploy
  - push_tags
  - build
  - javadoc
  - pages

deploy_to_yannouuuu_github:
  stage: deploy

  variables:
    GIT_DEPTH: 0
  script:
    - apt-get update && apt-get install -y git
    - git config --global user.email "yannrenard1025@gmail.com"
    - git config --global user.name "yannouuuu"
    - git remote rm github || true
    - git remote add github https://$GITHUB_TOKEN@github.com/yannouuuu/IUT-SAE2.01-2.02-RDBL
    - git push --force github HEAD:refs/heads/main
    - git push github --tags
  only:
    - main


build:
  stage: build
  script:
    - mvn clean package

javadoc:
  stage: javadoc
  script:
    - mvn javadoc:javadoc
  artifacts:
    paths:
      - target/site/apidocs/
    expire_in: 1 week

pages:
  stage: pages
  script:
    - mkdir -p public
    - cp -r target/site/apidocs/* public/
  artifacts:
    paths:
      - public
  only:
    - main