image: maven:3.9-eclipse-temurin-17

stages:
  - test
  - deploy_mirror
  - build
  - javadoc
  - pages

test:
  stage: test
  script:
    - apt-get update && apt-get install -y xvfb
    - xvfb-run mvn clean test
  artifacts:
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
    expire_in: 1 week

deploy_to_yannouuuu_github:
  stage: deploy_mirror
  variables:
    GIT_DEPTH: 0
  script:
    - apt-get update && apt-get install -y git
    - git config --global user.email "yannrenard1025@gmail.com"
    - git config --global user.name "yannouuuu"
    - git remote rm github || true
    - git remote add github https://$GITHUB_TOKEN@github.com/yannouuuu/IUT-SAE2.01-2.02-RDBL
    - git push --force github HEAD:refs/heads/main
    - git push --force github --tags
  only:
    - main

build:
  stage: build
  script:
    - mvn clean package -DskipTests
  artifacts:
    paths:
      - target/*.jar
    expire_in: 1 week

javadoc:
  stage: javadoc
  script:
    - mvn javadoc:javadoc
  artifacts:
    paths:
      - target/site/apidocs/

pages:
  stage: pages
  script:
    - mkdir -p public
    - cp -r target/site/apidocs/* public/
  artifacts:
    paths:
      - public
  only:
    - main